### PR TITLE
Fix incorrect getting version from siren check response

### PR DESCRIPTION
**Pull request by ObidosDev**
In code someone tried to get the version as a field of boolean value

### CODE REVIEW

**Comment by SudoPlz** [comment]
Hey @ObidosDev did you test that? Is it working? I wonder how that laid in there for that long.

**Comment by ObidosDev** [comment]
@SudoPlz I did not test it, I just have done sync with right version of `react-native-siren` lib and check by `console.log` current response structure :)

**Comment by ObidosDev** [comment]
@SudoPlz have a chance to get it soon?

**Comment by SudoPlz** [comment]
Yep I'll take a look today.

**Comment by SudoPlz** [comment]
This should be fixed in 1.0.3 (Note that there's a breaking change on how you import types for android) but there are no typings and your compiler should complain if you don't import the right type.
Check it out and let me know if everything works now.

**Comment by ObidosDev** [comment]
@SudoPlz looks like it was fixed in 1.0.3, but the typization is still not very good, but that's another story

**Comment by SudoPlz** [comment]
Glad to hear that @ObidosDev 
What's wrong with the typization? Types are working on my machine just fine. That being said, if you could open a PR I'd be happy to merge any fixes to types.

Thanks

**Pull request closed without merging**
