### PR TITLE
v1 alpha: Converting to typescript and adding examples

### PR DESCRIPTION
**Pull request by SudoPlz**
Attempt to rewrite library with typescript and add examples

### CODE REVIEW

**Comment by SudoPlz** [comment]
@Gustash Do you feel like helping out on this one?
I feel I mainly need help in the following sectors:

A) Typescript and properly exporting modules for the corresponding OS only:
`index.ios.js` and `index.android.js`  work wonderfully but when I attempt to `index.ios.ts` or `index.android.ts` all hell breaks loose.

It's important that we only import the Android native module on android, and the js module on ios, so using `*.<OS>.ts` really makes it cleaner, but doesn't work very well.
If on the other hand I leave those files as javascript we loose the types.

B) Also I need some help with making the Example actually work. Any ideas?
This library is supposed to work with actual store listings, but maybe we can somehow mock things up and make the example work here

C) Does anyone feel like adding some tests? I'd be grateful

**Comment by Gustash** [comment]
@SudoPlz as a reply to your questions:

1. We shouldn't do specific types for specific platforms. What we should do is document each part that is platform specific instead.

2. I'm not sure how worth mocking is. Maybe it's better if we just link Android documentation explaining what steps you need to do to test it. I think the example project is more code examples than anything.

3. Yes, we should write some tests for sure. I can look into it later.

I'll review this soon, currently a little busy but I should be able to make some time this week  :)

Good work man!

**Comment by SudoPlz** [comment]
Awesome, looking forward to it!

**Comment by SudoPlz** [comment]
Hey @Gustash did you get a chance to take a look?

**Comment by Gustash** [comment]
@SudoPlz hey, sorry about the delay, I've only had bits of time here and there to review this, and I still haven't gone through the whole thing since the PR is so large. I'll try to finish up the review today

**Pull request closed without merging**
