### PR TITLE
Fixed bug & Implemented Exception handling

### PR DESCRIPTION
**Pull request by abdollahzadehghalejoghi**
Hi 
This PR Including:
 1. fix `DEVELOPER_TRIGGERED` Status Bug in UPDATE_STATUS, Which was previously equal to `undefined`!
 2. Implemented `Exception handling`  for Android module. for when an error is received from [Google Play Store](https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode?authuser=1).
3. Added `installStatus` to the result object. required for [`resume flexible update`](https://developer.android.com/guide/playcore/in-app-updates#install_flexible)

### CODE REVIEW

**Review by SudoPlz — APPROVED** [review]

**Comment by SudoPlz** [comment]
I swear I added those in the past but I realise now they were never shipped.

Thanks for the PR @abdollahzadehghalejoghi  I appreciate it.

**Comment by SudoPlz** [comment]
Oh, I did add those in v1, but it's still undergoing a review

**Comment by abdollahzadehghalejoghi** [comment]
> Oh, I did add those in v1, but it's still undergoing a review

I still see some problems in v1,So I will correct it in v1 brunch

**Comment by abdollahzadehghalejoghi** [comment]
> I swear I added those in the past but I realise now they were never shipped.
> 
> Thanks for the PR @abdollahzadehghalejoghi I appreciate it.

It's important that everything is fine now.

**Pull request merged**
